### ISSUE TITLE
Codable protocol

### ISSUE THREAD

**Issue by cflorion** [agisboye/SwiftLMDB#17]
Hi :)

Is this only for basic types of is it possible to store a Codable struct in LMDB ? Or some Data maybe ?

**Comment by agisboye** [comment]
Anything that can be represented as `Data` can be used as a key or stored as a value in the database. So if your types are Codable you can convert them to Data and store them. :)

**Comment by cflorion** [comment]
Thanks a lot ! I will give that a try ;)
