### ISSUE TITLE
Get all Keys

### ISSUE THREAD

**Issue by justinmiller62** [agisboye/SwiftLMDB#20]
Is there a way to get a listing/array of all the keys on the database?

**Comment by agisboye** [comment]
Not at the moment. I have plans to implement cursors, which would also allow you to quickly build a list of all keys in the database.

**Comment by agisboye** [comment]
Cursors for read operations have been implemented since 2.1.0.
`Database` now conforms to `Sequence` so you can get all keys like this:
```swift
let keys = database.map { $0.key }
```
