### ISSUE TITLE
Is Database.get implemented correctly? 

### ISSUE THREAD

**Issue by kennycarruthers** [agisboye/SwiftLMDB#21]
Apologies for the vague title... 

Just started playing around with SwiftLMDB and I was curious if `Database.get` was implemented correctly based on my interpretation of the documentation. 

[Database.get](https://github.com/agisboye/SwiftLMDB/blob/2127dae33e07251c442041f8e6329ae4f874366f/Sources/Database.swift#L114) calls `mdb_get` inside a `Transaction` closure. There is a comment above that points to LMDB's documentation referencing the fact that LMDB will manage the returned memory. 

> The memory pointed to by the returned values is owned by the database. The caller need not dispose of the memory, and may not modify it in any way. 
> 
> For values returned in a read-only transaction any modification attempts will cause a SIGSEGV.
> Values returned from the database are valid only until a subsequent update operation, **or the end of the transaction**.

I interpret this to imply that once the `Transaction` closure finishes, then `var dataVal` should no longer be considered valid. Which means that read it's `mv_data` property on line 126 might not be correct. 

Shouldn't [this line](https://github.com/agisboye/SwiftLMDB/blob/2127dae33e07251c442041f8e6329ae4f874366f/Sources/Database.swift#L126)  be inside the `Transaction` closure? 

`let data = Data(bytes: dataVal.mv_data, count: dataVal.mv_size)` 

Happy to be proven wrong, just something I noticed while scanning through the code and learning more about LMDB. Thanks for the project and contributions. 

(I should add that I actually haven't seen any crashes or issues with this.)

**Comment by agisboye** [comment]
I think you're right. It's a race condition, and I think it would only manifest itself if you manage to update a value (from another thread) in the window between performing the read transaction and copying the data. I've never seen it in production but I'm happy to have it fixed. Thanks!

Fixed in [7472c09](https://github.com/agisboye/SwiftLMDB/commit/7472c095811af128a50b4096b613edfced190cbc) and tagged as version [2.1.1](https://github.com/agisboye/SwiftLMDB/releases/tag/2.1.1).

**Comment by kennycarruthers** [comment]
Nice. That's about how I would have changed it as well. I agree that it's unlikely to have been a problem before, but this new implementation is probably "more correct" based on LMDB's documentation. 

I can't really test this because it wasn't actually failing for me before, but the change seems reasonable so I'd probably close this issue depending on how you like to manage this project. 

Thanks for the quick fix and update.
