### ISSUE TITLE
Environment.deinit can crash when closing the environment handle. 

### ISSUE THREAD

**Issue by kennycarruthers** [agisboye/SwiftLMDB#22]
`Environment.deinit` always calls `mdb_env_close(handle)`. However, if `mdb_env_open` fails on line 82, then the `guard` condition is entered and the handle is closed then an exception is thrown. 

That exception might be caught higher up in such a way that the Environment is released and `deinit` is called, causing the handle to get released a second time and crashing. 

In my case, the database failed to open because it did not have sufficient permissions for the target directory. The exception was caught and an error might be presented to the user, but since the `Environment` is released the application crashes. 

Looks like it might be "safe" to just omit releasing the handle in the `guard` and instead relying on `deinit` as that seems to be the case for all other exceptions thrown in the initializer.

**Comment by agisboye** [comment]
Good catch! I just encountered this issue myself for the first time. 
Fixed in [2.1.2](https://github.com/agisboye/SwiftLMDB/releases/tag/2.1.2).
