### ISSUE TITLE
Does LMDB work in a sandboxed application? 

### ISSUE THREAD

**Issue by kennycarruthers** [agisboye/SwiftLMDB#23]
I'm playing around with LMDB and this library and just tried to use it in a bare-bones macOS application that is sandboxed. However, the database is not opening and `mdb_env_open` is return 1 (EPERM), suggesting there's a permission problem somewhere. 

However the path I'm passing it is within my application's Container. The db lock file is getting created but then something is failing. If this works on iOS then I would assume it should work for macOS sandboxed apps as well. 

Just curious if there's any insight on that. 

To test, just create a new macOS app in Xcode and try to open a database in your application's support directory as provided by `FileManager`.

**Comment by kennycarruthers** [comment]
Follow-up: 

Looks like LMDB needs to be compiled with POSIX semaphores enabled and the semaphore prefix needs to match your application's app-group. By default, LMDB is compiled to use System V semaphores which are not supported in a sandboxed application. 

Some of this is referenced at the bottom of this document: 

https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW24

**Comment by kennycarruthers** [comment]
Recommend you just close this issue as it is not directly related to SwiftLMDB but rather to LMDB itself. I also note that semaphores are discussed in issue #4. There appears to still be some issues getting them to work properly on macOS in a sandboxed application but I think that's outside the scope of this project.

**Comment by agisboye** [comment]
I've only used SwiftLMDB in iOS apps, however, like you said, if it works in the iOS sandbox, I would expect it to work on macOS as well.

In SwiftLMDB, LMDB is already being compiled with POSIX semaphores enabled:
[https://github.com/agisboye/CLMDB/blob/24fd75459dd82fee490a2609c80a8def94fc695c/Sources/LMDB/include/clmdb.h#L4](https://github.com/agisboye/CLMDB/blob/24fd75459dd82fee490a2609c80a8def94fc695c/Sources/LMDB/include/clmdb.h#L4)

If you find a workaround, let me know.

**Comment by kennycarruthers** [comment]
I struggled to get it working on macOS and then moved on to something else. I think you just have to figure out the right combination of entitlements, App Groups and Xcode configuration settings. Originally, I was getting `EPERM` errors (status code 1) but once I had App Groups working I was getting `ENAMETOOLONG` (status code 63) errors. 

The macOS Sandbox is rather finicky so I'm not surprised there are some issues. Regardless, as noted above, I don't think this is necessarily an issue with `SwiftLMDB`.

**Comment by jflow** [comment]
Experiencing this as well on sandboxed macOS app. Trying to create a database in the app container documents folder and get a lock.mdb and a EPERM error.

**Comment by agisboye** [comment]
Sorry - I'm not too familiar with the macOS sandbox. It could be related to LMBD's use of POSIX semaphores. I don't think it necessarily follows the naming conventions specified here:
[IPC and POSIX Semaphores and Shared Memory](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW24)

If you manage to find a solution, please open a PR. 😊

**Comment by hyc** [comment]
@agisboye the documentation link you provided doesn't seem to work now. Have you got a copy of the relevant info, or an up to date link?

**Comment by agisboye** [comment]
Hi @hyc,
What an honor having you here. 😊

It looks like Apple replaced the article with their new documentation, which doesn't seem to provide the same amount of detail. The old docs can be accessed through the Internet Archive [here](https://web.archive.org/web/20220726203624/https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html). The section I referenced is at the bottom.

**Comment by hyc** [comment]
Thanks. Gonna paste it here for convenience:

> IPC and POSIX Semaphores and Shared Memory

> Normally, sandboxed apps cannot use Mach IPC, POSIX semaphores and shared memory, or UNIX domain sockets (usefully). However, by specifying an entitlement that requests membership in an application group, an app can use these technologies to communicate with other members of that application group.

> Note: System V semaphores are not supported in sandboxed apps.

> UNIX domain sockets are straightforward; they work just like any other file.

> Any semaphore or Mach port that you wish to access within a sandboxed app must be named according to a special convention:

>    POSIX semaphores and shared memory names must begin with the application group identifier, followed by a slash (/), followed by a name of your choosing.

>    Mach port names must begin with the application group identifier, followed by a period (.), followed by a name of your choosing.

> For example, if your application group’s name is Z123456789.com.example.app-group, you might create two semaphores named Z123456789.myappgroup/rdyllwflg and Z123456789.myappgroup/bluwhtflg. You might create a Mach port named Z123456789.com.example.app-group.Port_of_Kobe.

> Note: The maximum length of a POSIX semaphore name is only 31 bytes, so if you need to use POSIX semaphores, you should keep your app group names short.



It sounds to me like if you want this to work you're going to need to patch your own builds of LMDB to include your application group name. With that 31-byte limit I don't even see much point to making this settable via LMDB API.

The other possibility is to just give up on trying to support multi-process concurrency, and use a standard mutex instead of an interprocess mechanism. That decision probably depends on whether you actually have a group of cooperating apps in the app group or not.

**Comment by tannerdsilva** [comment]
Apples documentation continues to get worse and more vague. Very annoying.

Thanks for your support, @hyc. I saw your responses in [the ticket](https://bugs.openldap.org/show_bug.cgi?id=10043) as well. This definitely seems like the type of issue that the more platform-oriented projects (wrappers) would take on.

@agisboye if you are seriously motivated to try supporting this use case, I would be inclined and willing to provide my time in supporting you however I can, towards building the solution. However, under my own means, not feeling the capacity to get my library dancing around this issue right now. I’ll likely be closing the issue in my project.

**Comment by agisboye** [comment]
Thanks both @hyc and @tannerdsilva. I don't have any motivation for supporting this use case as I only use the library in iOS apps. If anyone figures out a solution and wants to contribute a PR, I'd be happy to take a look at it.

**Comment by rosstulloch** [comment]
Just FYI. In my sandboxed macOS app, I'm using MDB_NOLOCK (Environment.Flags.noLock) when opening the DB and a serialised work queue when accessing it. That's all I need for my use case. Results so far are excellent.
