### ISSUE TITLE
Database used space

### ISSUE THREAD

**Issue by claudiu82** [agisboye/SwiftLMDB#24]
Hello !

First of all I would like to thank you all for all your work to bring LMDB into Swift. 
This is not a issue report but more like a feature request.
Can you please add a used space variable to Database class, or at least a public available variable for MDB_stat() ?
Also I think a public variable for the LMDB version would be useful sometime in the future.

Thank you !

**Comment by agisboye** [comment]
Hi,

Thanks for your suggestions. The version is already available as a [property on SwiftLMDB](https://github.com/agisboye/SwiftLMDB/blob/93707ff1bcfed4b2bc4c945499ce2577f39c381e/Sources/SwiftLMDB.swift#L16).

I've added a [stats](https://github.com/agisboye/SwiftLMDB/blob/30c84466ebf267c49daf1a453983cde876007bb0/Sources/Database.swift#L49) property. You should be able to use the information within to compute the size of the database.

**Comment by claudiu82** [comment]
Hello !

Thank you very much for your quick response and for this amazing tool.

Best regards,
Claudiu
