### ISSUE TITLE
`SwiftLMDB` struct conflicts with the package name

### ISSUE THREAD

**Issue by corujautx** [agisboye/SwiftLMDB#25]
Heya, first of all, love your wrapper!

So I'm having trouble with the `SwiftLMDB` struct. I have an actor named `Database` in the project I'm adding `SwiftLMDB` into. The problem is to abstract `SwiftLMDB` I need to differentiate the `Database` class from the package from the one in my project, and the `SwiftLMDB` **struct** is shadowing the package import name 😱 

Is it possible to change the **struct** name? I think from Swift 6 onwards that will be illegal too iirc (at least to generics).

I'll probably fork and open a PR changing from `SwiftLMDB` **struct** to `LMDB` or `CLMDB` or a global constant (not sure what's the best, I'll have a look when I fork), but just kicking in the discusison here.

Thanks for the wrapper once again.

**Comment by agisboye** [comment]
Thanks for this! I've published 2.2.0 with these changes. 🙏🏼
