### ISSUE TITLE
Swift Package Manager cannot find dependency

### ISSUE THREAD

**Issue by placrosse** [agisboye/SwiftLMDB#5]
Adding this:
       .Package(url: "https://github.com/agisboye/SwiftLMDB.git", majorVersion: 0, minor: 0),

Results in this:
ubuntu@ubuntu-xenial:~/src/Multivariator$ swift build
Fetching https://github.com/agisboye/SwiftLMDB.git
error: unsatisfiable

Due to no tagged release version, as explained in:
https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#publish-a-package

Without the tag, usage as a dependency fails (tested under Ubuntu Linux 16.04).

**Comment by agisboye** [comment]
A tag has been added 👍
