### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by placrosse** [agisboye/SwiftLMDB#6]
ubuntu@ubuntu-xenial:~/src/SwiftLMDB$ uname -a
Linux ubuntu-xenial 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@ubuntu-xenial:~/src/SwiftLMDB$ swift test
Compile CLMDB midl.c
Compile CLMDB mdb.c
/home/ubuntu/src/SwiftLMDB/.build/checkouts/CLMDB.git--4447338618528579073/Sources/mdb.c:10918:46: warning: data argument not used by format string [-Wformat-extra-args]
                                (int)mr[i].mr_pid, (size_t)mr[i].mr_tid, txnid);
                                                                         ^
1 warning generated.
Linking CLMDB
Compile Swift Module 'SwiftLMDB' (6 sources)
Compile Swift Module 'SwiftLMDBTests' (1 sources)
Linking ./.build/debug/SwiftLMDBPackageTests.xctest
Test Suite 'All tests' started at 21:03:26.125
Test Suite 'debug.xctest' started at 21:03:26.125
Test Suite 'SwiftLMDBTests' started at 21:03:26.125
Test Case 'SwiftLMDBTests.testGetLMDBVersion' started at 21:03:26.125
Test Case 'SwiftLMDBTests.testGetLMDBVersion' passed (0.0 seconds)
Test Case 'SwiftLMDBTests.testCreateEnvironment' started at 21:03:26.125
Test Case 'SwiftLMDBTests.testCreateEnvironment' passed (0.002 seconds)
Test Case 'SwiftLMDBTests.testCreateUnnamedDatabase' started at 21:03:26.127
Test Case 'SwiftLMDBTests.testCreateUnnamedDatabase' passed (0.0 seconds)
Test Case 'SwiftLMDBTests.testHasKey' started at 21:03:26.127
/home/ubuntu/src/SwiftLMDB/Tests/SwiftLMDBTests/SwiftLMDBTests.swift:109: error: SwiftLMDBTests.testHasKey : XCTAssertTrue failed - No value has been set for this key. Result should be false.
Test Case 'SwiftLMDBTests.testHasKey' failed (0.002 seconds)
Test Case 'SwiftLMDBTests.testPutGetString' started at 21:03:26.130
/home/ubuntu/src/SwiftLMDB/Tests/SwiftLMDBTests/SwiftLMDBTests.swift:149: error: SwiftLMDBTests.testPutGetString : XCTAssertTrue failed - No value has been set for this key. Result should be false.
Test Case 'SwiftLMDBTests.testPutGetString' failed (0.001 seconds)
Test Case 'SwiftLMDBTests.testEmptyKey' started at 21:03:26.131
Test Case 'SwiftLMDBTests.testEmptyKey' passed (0.0 seconds)
Test Case 'SwiftLMDBTests.testPutGetDouble' started at 21:03:26.131
/home/ubuntu/src/SwiftLMDB/Tests/SwiftLMDBTests/SwiftLMDBTests.swift:213: error: SwiftLMDBTests.testPutGetDouble : failed - No value was found for the key.
Test Case 'SwiftLMDBTests.testPutGetDouble' failed (0.001 seconds)
Test Case 'SwiftLMDBTests.testPutGetArray' started at 21:03:26.132
/home/ubuntu/src/SwiftLMDB/Tests/SwiftLMDBTests/SwiftLMDBTests.swift:253: error: SwiftLMDBTests.testPutGetArray : failed - No value was found for the key.
Test Case 'SwiftLMDBTests.testPutGetArray' failed (0.001 seconds)
Test Case 'SwiftLMDBTests.testDelete' started at 21:03:26.132
Test Case 'SwiftLMDBTests.testDelete' passed (0.0 seconds)
Test Case 'SwiftLMDBTests.testDropDatabase' started at 21:03:26.133
Test Case 'SwiftLMDBTests.testDropDatabase' passed (0.001 seconds)
Test Case 'SwiftLMDBTests.testEmptyDatabase' started at 21:03:26.133
Test Case 'SwiftLMDBTests.testEmptyDatabase' passed (0.001 seconds)
Test Suite 'SwiftLMDBTests' failed at 21:03:26.134
	 Executed 11 tests, with 4 failures (0 unexpected) in 0.009 (0.009) seconds
Test Suite 'debug.xctest' failed at 21:03:26.134
	 Executed 11 tests, with 4 failures (0 unexpected) in 0.009 (0.009) seconds
Test Suite 'All tests' failed at 21:03:26.134
	 Executed 11 tests, with 4 failures (0 unexpected) in 0.009 (0.009) seconds

**Comment by placrosse** [comment]
Also used the demo code to put and get, and had similar problem to failed tests, in that key not found, which was just successfully put.

**Comment by agisboye** [comment]
The library compiles - thats great. I'm aware that some of the tests are failing on Linux. The issue appears to be that the temporary directory is not being created properly. 

https://github.com/agisboye/SwiftLMDB/blob/3ac09613730fe3f09dffce12c8f7d287d934ed56/Tests/SwiftLMDBTests/SwiftLMDBTests.swift#L21
